export const SAMPLE_PRODUCTS = [
  {
    id: "1",
    name: "Glow Serum Pro",
    description: "Vitamin C serum for radiant skin. Dermatologist tested.",
    price: 29.99,
    imageUrls: ["/placeholder-product.jpg"],
    niche: "beauty-skincare",
    commissionPct: 18,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Wireless Earbuds X",
    description: "Noise-cancelling, 24hr battery. Premium sound.",
    price: 79.99,
    imageUrls: ["/placeholder-product.jpg"],
    niche: "tech-gadgets",
    commissionPct: 12,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Yoga Mat Elite",
    description: "Eco-friendly non-slip mat. Extra thick for comfort.",
    price: 34.99,
    imageUrls: ["/placeholder-product.jpg"],
    niche: "fitness-wellness",
    commissionPct: 15,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Minimalist Watch",
    description: "Slim design, stainless steel. Water resistant.",
    price: 59.99,
    imageUrls: ["/placeholder-product.jpg"],
    niche: "fashion",
    commissionPct: 20,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Smart LED Strip",
    description: "RGB mood lighting. Voice control compatible.",
    price: 24.99,
    imageUrls: ["/placeholder-product.jpg"],
    niche: "home-decor",
    commissionPct: 14,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Pet Grooming Kit",
    description: "Brush, shampoo, and nail clippers. All-in-one.",
    price: 19.99,
    imageUrls: ["/placeholder-product.jpg"],
    niche: "pet-products",
    commissionPct: 16,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];
